name: Version Next
description: |
  Action to version the next release/artifact of a project using semantic-release.
inputs:
  use-default-config:
    description: Use default semantic-release config
    required: false
    default: 'false'
  dry-run:
    description: Run semantic-release in dry-run mode
    required: false
    default: 'true'
  token:
    description: Github token
    required: true
  slack_webhook:
    description: Slack webhook url
    required: true
  fail:
    description: Fail if no version is detected
    required: false
    default: 'true'
  working-dir:
    description: Working directory for semantic-release operations
    required: false
    default: '.'
outputs:
  version:
    description: 'new version detected by semantic-release'
    value: ${{ steps.new_version_sr.outputs.version }}
runs:
  using: 'composite'
  steps:
    - name: Setup semantic-release config
      if: ${{ inputs.use-default-config == 'false' }}
      shell: python
      # language=python
      run: |
        import os

        working_dir = '${{ inputs.working-dir }}'
        if working_dir and working_dir != '.':
            os.chdir(working_dir)

        config = '.releaserc.json'
        if os.path.exists(config):
            print(f'{config} exists')
        else:
            with open(config, 'w') as f:
                f.write(
                    '''{
                      "branches": [
                        "main"
                      ],
                      "tagFormat": "${version}",
                      "plugins": [
                        "@semantic-release/commit-analyzer",
                        "@semantic-release/release-notes-generator",
                        "@semantic-release/github",
                        [
                          "@semantic-release/exec",
                          {
                            "verifyReleaseCmd": "echo ${nextRelease.version} > .VERSION"
                          }
                        ]
                      ]
                    }
                '''
                )
            print(f'{config} created')

    - name: "Semantic Release: Dry Run"
      shell: bash
      if: ${{ inputs.dry-run == 'true' }}
      working-directory: ${{ inputs.working-dir }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        SEMANTIC_RELEASE_PACKAGE: ${{ github.repository}}
      #language="bash"
      run: |
        npx -p semantic-release-slack-bot -p @semantic-release/exec semantic-release --dry-run

    - name: "Semantic Release"
      shell: bash
      if: ${{ inputs.dry-run == 'false' }}
      working-directory: ${{ inputs.working-dir }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GH_TOKEN: ${{ inputs.token }}
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        SEMANTIC_RELEASE_PACKAGE: ${{ github.repository}}
      #language="bash"
      run: |
        npx -p semantic-release-slack-bot -p @semantic-release/exec semantic-release

    - name: check if version presented
      if: ${{ inputs.fail == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      #language="bash"
      run: |
        export VERSION="$(cat .VERSION)"
        if [ -z "$VERSION" ]; then
          echo "Version variable is empty. Please check if \".releaserc.json\" contains next line: [ \"@semantic-release/exec\",  { \"verifyReleaseCmd\": \"echo \${nextRelease.version} > .VERSION\" } ] "
          echo "Also check if your commit message is correct and applicable to semantic-release/conventional commits"
          exit 1
        fi

    - name: Extract version from Git tags
      id: new_version_sr
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      #language="bash"
      run: |
        export VERSION="$(cat .VERSION)"        
        echo "Next version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT
