name: verify commits with commitlint
description: |
  Verify commits with commitlint according to the provided configuration.
inputs:
  modules:
    description: modules to install
    required: true
    default: "@commitlint/config-conventional,@commitlint/config-angular"
  publish:
    description: publish the commitlint as GH check
    required: false
    default: 'false'
  token:
    description: GitHub Token
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      #language=bash
      run: |
        IFS=',' read -ra MODULES <<< "${{ inputs.modules }}"
        for module in "${MODULES[@]}"; do
          echo "Installing $module globally..."
          npm install -g "$module"
        done
        echo "All modules installed: ${{ inputs.modules }}"

    - name: Validate PR commits with commitlint
      shell: bash
      id: commitlint
      continue-on-error: true
      #language=bash
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "Validating PR commits with commitlint..."
          COMMITLINT_ARGS="--from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}"
        else
          COMMITLINT_ARGS="--last"
        fi
        
        if npx commitlint $COMMITLINT_ARGS --verbose &> commitlint.log; then
          echo "status=success" >> "$GITHUB_OUTPUT"
        else
          echo "status=failure" >> "$GITHUB_OUTPUT"
        fi

    - shell: bash
      #language=bash
      run: |
        cat commitlint.log

    - name: "Create a check run"
      uses: actions/github-script@v6
      with:
        #language=javascript
        script: |
          // Read the commitlint.log content
          const fs = require('fs');
          const commitlintLog = fs.readFileSync('commitlint.log', 'utf8');
          
          const pullRequest = context.payload.pull_request
          const conclusion = "${{ steps.commitlint.outputs.status }}"
          const headSha = (pullRequest && pullRequest.head.sha) || context.sha
          const link = pullRequest?.html_url || "[no PR link]"
          core.info(`ℹ️ Posting with conclusion '${conclusion}' to ${link} (sha: ${headSha}) commitlint: ${{ steps.commitlint.outputs.status }}`)

          await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head_sha: headSha,
            name: "🌚 Commitlint",
            status: "completed",
            conclusion: conclusion,
            output: {
              title: "🌚Commitlint",
              summary: `commit lint config used: commitlint.config.cjs`,
              text: commitlintLog
            }
          });
