name: Scan Container with Trivy
description: More https://github.com/aquasecurity/trivy-action
inputs:
  dockerfile:
    description: docker file to build
    default: "Dockerfile"
    required: true
  image:
    description: image
    required: true
  gh_token:
    description: docker context
    required: true
runs:
  using: 'composite'
  steps:
    - name: "👀 Trivy: Scan Docker Image"
      uses: aquasecurity/trivy-action@0.29.0
      with:
        image-ref: '${{ inputs.image }}'
        format: 'template'
        template: "@$HOME/.local/bin/trivy-bin/contrib/junit.tpl"
        exit-code: '0'
        ignore-unfixed: true
        output: 'trivy-results.sarif'
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        github-pat: ${{ inputs.gh_token }}

    - name: "tune name"
      shell: bash
      # language="bash"
      run: |
        export IMAGE_SHORT="${{ inputs.image }}"
        echo "IMAGE_SHORT=$( echo $IMAGE_SHORT | sed 's/ghcr.io\///' )" >> $GITHUB_ENV

    - name: Scan Dockerfile
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'config'
        scan-ref: '${{ inputs.dockerfile }}'
        trivy-config: trivy.yaml
        template: "@$HOME/.local/bin/trivy-bin/contrib/junit.tpl"
        exit-code: '0'
        ignore-unfixed: true
        output: 'trivy-results.config.sarif'

    - name: "🎁 Publish Trivy Image"
      uses: mikepenz/action-junit-report@v5
      with:
        check_name: '🐳 Trivy: ${{ env.IMAGE_SHORT }}'
        report_paths: trivy-results.sarif
        annotate_only: false

    - name: "🎁 Publish Trivy Dockerfile"
      uses: mikepenz/action-junit-report@v5
      with:
        check_name: '🐳 Trivy: ${{ inputs.dockerfile}}'
        report_paths: trivy-results.config.sarif
        annotate_only: false
